FROM haxe:4.3.5-bullseye

ENV LANG=en_US.utf8
ENV LANGUAGE=en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y unzip
RUN apt-get install -y zip
RUN apt-get install -y gcc
RUN apt-get install -y g++

# ruby & gem
RUN apt-get install -y wget
RUN apt-get install -y make
RUN apt-get install -y ruby-full
RUN apt-get install zlib1g-dev
RUN gem install bundler -v 2.3.26

# Install Java
RUN apt-get install -y default-jdk
ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

# INSTALLING NODEJS
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN apt-get install -y nodejs

ENV NODE_PATH=/usr/lib/node_modules
ENV NODE_OPTIONS=--max_old_space_size=4096


# HAXELIB SETUP
RUN mkdir -p /haxelib
RUN haxelib setup /haxelib

# HAXER LIBS
RUN yes | haxelib install utest
RUN yes | haxelib install datetime
RUN yes | haxelib install hxcpp
RUN yes | haxelib install hxjava
RUN yes | haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git

# NODEJS LIBS
RUN npm install -g nodemon@2.0.20

WORKDIR /util-kit

CMD ["sh", "/docker-shared/alive.sh"]
